import type { PR } from './store';

export const DEMO_REPOS = ['facebook/react', 'vercel/next.js', 'tailwindlabs/tailwindcss'];

export const DEMO_USERS = [
  'andrew-burton',
  'sarah-chen',
  'marcus-johnson',
  'elena-rodriguez',
  'david-kim',
  'priya-patel',
  'james-mitchell',
  'lisa-anderson',
];

export const DEMO_CURRENT_USER = 'sarah-chen';

export function buildDemoPRs(): PR[] {
  const now = Date.now();
  const day = 86400000;

  return [
    {
      id: 1, number: 4271, draft: false,
      title: 'feat: Add webhook retry with exponential backoff',
      html_url: 'https://github.com/facebook/react/pull/4271',
      repository_url: 'https://github.com/facebook/react',
      url: 'https://github.com/facebook/react',
      user: { login: 'andrew-burton' },
      labels: [{ name: 'enhancement', color: 'a2eeef' }, { name: 'needs review', color: 'fbca04' }],
      body: '## Summary\n\nAdds exponential backoff retry logic to webhook delivery.\n\n- Retry on 5xx responses\n- Configurable max retries\n- Jitter for thundering herd\n\nCloses #4255.',
      mergeable_state: 'clean',
      buildStatus: { state: 'completed', conclusion: 'success' },
      reviews: [
        { state: 'APPROVED', user: { login: 'sarah-chen' }, submitted_at: new Date(now - day * 0.5).toISOString() },
        { state: 'COMMENTED', user: { login: 'david-kim' }, submitted_at: new Date(now - day * 0.3).toISOString() },
      ],
      comments: [{ user: { login: 'david-kim' }, created_at: new Date(now - day * 0.3).toISOString(), body: 'Nice approach. Have you considered adding config for the base delay?' }],
      files: [
        { filename: 'src/webhook/retry.ts', additions: 120, deletions: 10, changes: 130, status: 'added' },
        { filename: 'src/webhook/delivery.ts', additions: 45, deletions: 20, changes: 65, status: 'modified' },
        { filename: 'src/webhook/config.ts', additions: 30, deletions: 5, changes: 35, status: 'modified' },
      ],
      additions: 195, deletions: 35, changed_files: 3,
      complexity: 42, effort: 18,
      complexityBreakdown: { score: 42, label: 'moderate', totalFiles: 3, relevantFiles: 3, ignoredFiles: 0, totalAdditions: 195, totalDeletions: 35, weightedChurn: 130, fileSpread: 3, intensity: 0.4, topFiles: [{ filename: 'src/webhook/retry.ts', weight: 1.0, churn: 120, contribution: 61 }] },
      created_at: new Date(now - day * 5).toISOString(),
      updated_at: new Date(now - day * 0.5).toISOString(),
    },
    {
      id: 2, number: 4268, draft: false,
      title: 'fix: Token refresh race condition on expiry',
      html_url: 'https://github.com/facebook/react/pull/4268',
      repository_url: 'https://github.com/facebook/react',
      url: 'https://github.com/facebook/react',
      user: { login: 'sarah-chen' },
      labels: [{ name: 'bug', color: 'd73a4a' }, { name: 'priority-high', color: 'b60205' }],
      body: 'Fixes a race condition where concurrent requests could trigger multiple token refreshes, causing 429 errors.\n\nRoot cause: missing mutex around refresh call.',
      mergeable_state: 'clean',
      buildStatus: { state: 'completed', conclusion: 'success' },
      reviews: [
        { state: 'APPROVED', user: { login: 'marcus-johnson' }, submitted_at: new Date(now - day * 1).toISOString() },
        { state: 'APPROVED', user: { login: 'elena-rodriguez' }, submitted_at: new Date(now - day * 0.8).toISOString() },
      ],
      comments: [],
      files: [
        { filename: 'src/auth/token-manager.ts', additions: 85, deletions: 40, changes: 125, status: 'modified' },
        { filename: 'src/auth/__tests__/token-manager.test.ts', additions: 60, deletions: 15, changes: 75, status: 'modified' },
      ],
      additions: 145, deletions: 55, changed_files: 2,
      complexity: 28, effort: 12,
      complexityBreakdown: { score: 28, label: 'moderate', totalFiles: 2, relevantFiles: 2, ignoredFiles: 0, totalAdditions: 145, totalDeletions: 55, weightedChurn: 85, fileSpread: 2, intensity: 0.3, topFiles: [{ filename: 'src/auth/token-manager.ts', weight: 1.0, churn: 85, contribution: 100 }] },
      created_at: new Date(now - day * 7).toISOString(),
      updated_at: new Date(now - day * 0.8).toISOString(),
    },
    {
      id: 3, number: 4255, draft: false,
      title: 'Upgrade Node runtime from 18 to 22',
      html_url: 'https://github.com/facebook/react/pull/4255',
      repository_url: 'https://github.com/facebook/react',
      url: 'https://github.com/facebook/react',
      user: { login: 'marcus-johnson' },
      labels: [{ name: 'infra', color: '006b75' }, { name: 'breaking', color: 'e99695' }],
      body: 'Updates the Node.js runtime from 18.x to 22.x across all services.\n\nMigration guide included in PR description.',
      mergeable_state: 'dirty',
      buildStatus: { state: 'completed', conclusion: 'failure' },
      reviews: [
        { state: 'CHANGES_REQUESTED', user: { login: 'sarah-chen' }, submitted_at: new Date(now - day * 1.5).toISOString(), body: 'We need to update the CI matrix to test both versions during the transition period.' },
        { state: 'COMMENTED', user: { login: 'andrew-burton' }, submitted_at: new Date(now - day * 1.8).toISOString() },
      ],
      comments: [{ user: { login: 'andrew-burton' }, created_at: new Date(now - day * 1.8).toISOString(), body: 'There are a few deprecated APIs we use that are removed in 22. See comment in Dockerfile.' }],
      files: [
        { filename: 'Dockerfile', additions: 2, deletions: 2, changes: 4, status: 'modified' },
        { filename: '.nvmrc', additions: 1, deletions: 1, changes: 2, status: 'modified' },
        { filename: '.github/workflows/ci.yml', additions: 15, deletions: 5, changes: 20, status: 'modified' },
        { filename: 'scripts/migrate-node.mjs', additions: 200, deletions: 0, changes: 200, status: 'added' },
      ],
      additions: 218, deletions: 8, changed_files: 4,
      complexity: 15, effort: 8,
      complexityBreakdown: { score: 15, label: 'low', totalFiles: 4, relevantFiles: 2, ignoredFiles: 2, totalAdditions: 218, totalDeletions: 8, weightedChurn: 15, fileSpread: 4, intensity: 0.1, topFiles: [{ filename: 'scripts/migrate-node.mjs', weight: 0.2, churn: 0, contribution: 0 }] },
      created_at: new Date(now - day * 10).toISOString(),
      updated_at: new Date(now - day * 1.5).toISOString(),
    },
    {
      id: 4, number: 4232, draft: false,
      title: 'Dark mode support for dashboard',
      html_url: 'https://github.com/facebook/react/pull/4232',
      repository_url: 'https://github.com/facebook/react',
      url: 'https://github.com/facebook/react',
      user: { login: 'elena-rodriguez' },
      labels: [{ name: 'feature', color: '0e8a16' }],
      body: 'Adds a dark mode theme toggle to the settings page.\n\nUses CSS custom properties for seamless switching.',
      mergeable_state: 'clean',
      buildStatus: { state: 'in_progress', conclusion: undefined },
      reviews: [],
      comments: [],
      files: [
        { filename: 'src/components/ThemeToggle.tsx', additions: 85, deletions: 0, changes: 85, status: 'added' },
        { filename: 'src/styles/themes.css', additions: 120, deletions: 0, changes: 120, status: 'added' },
        { filename: 'src/hooks/useTheme.ts', additions: 45, deletions: 0, changes: 45, status: 'added' },
      ],
      additions: 250, deletions: 0, changed_files: 3,
      complexity: 24, effort: 10,
      complexityBreakdown: { score: 24, label: 'low', totalFiles: 3, relevantFiles: 3, ignoredFiles: 0, totalAdditions: 250, totalDeletions: 0, weightedChurn: 85, fileSpread: 3, intensity: 0.2, topFiles: [{ filename: 'src/styles/themes.css', weight: 0.8, churn: 120, contribution: 47 }] },
      created_at: new Date(now - day * 3).toISOString(),
      updated_at: new Date(now - day * 0.5).toISOString(),
    },
    {
      id: 5, number: 4218, draft: true,
      title: 'Refactor Button component variants',
      html_url: 'https://github.com/facebook/react/pull/4218',
      repository_url: 'https://github.com/facebook/react',
      url: 'https://github.com/facebook/react',
      user: { login: 'david-kim' },
      labels: [{ name: 'refactor', color: '9c27b0' }],
      body: 'Consolidates Button, IconButton, and LinkButton into a single polymorphic component.\n\nWIP: Need to update tests.',
      mergeable_state: 'clean',
      buildStatus: { state: 'pending', conclusion: undefined },
      reviews: [],
      comments: [{ user: { login: 'priya-patel' }, created_at: new Date(now - day * 2).toISOString(), body: 'Love the polymorphic approach. Do we need to deprecate the old components or can we do a direct swap?' }],
      files: [
        { filename: 'src/components/Button/index.tsx', additions: 200, deletions: 350, changes: 550, status: 'modified' },
        { filename: 'src/components/IconButton.tsx', additions: 0, deletions: 80, changes: 80, status: 'deleted' },
        { filename: 'src/components/LinkButton.tsx', additions: 0, deletions: 60, changes: 60, status: 'deleted' },
      ],
      additions: 200, deletions: 490, changed_files: 3,
      complexity: 55, effort: 25,
      complexityBreakdown: { score: 55, label: 'high', totalFiles: 3, relevantFiles: 3, ignoredFiles: 0, totalAdditions: 200, totalDeletions: 490, weightedChurn: 350, fileSpread: 3, intensity: 0.7, topFiles: [{ filename: 'src/components/Button/index.tsx', weight: 1.0, churn: 350, contribution: 90 }] },
      created_at: new Date(now - day * 6).toISOString(),
      updated_at: new Date(now - day * 1).toISOString(),
    },
    {
      id: 6, number: 4205, draft: false,
      title: 'Optimize virtual list rendering for large datasets',
      html_url: 'https://github.com/vercel/next.js/pull/9201',
      repository_url: 'https://github.com/vercel/next.js',
      url: 'https://github.com/vercel/next.js',
      user: { login: 'priya-patel' },
      labels: [{ name: 'performance', color: '008672' }],
      body: 'Switches the virtual list from react-window to a custom implementation using IntersectionObserver.\n\n30% faster initial render for 10k+ item lists.',
      mergeable_state: 'clean',
      buildStatus: { state: 'completed', conclusion: 'success' },
      reviews: [
        { state: 'APPROVED', user: { login: 'james-mitchell' }, submitted_at: new Date(now - day * 0.2).toISOString() },
        { state: 'APPROVED', user: { login: 'andrew-burton' }, submitted_at: new Date(now - day * 0.1).toISOString() },
      ],
      comments: [],
      files: [
        { filename: 'src/components/VirtualList.tsx', additions: 310, deletions: 0, changes: 310, status: 'added' },
        { filename: 'src/hooks/useVirtualization.ts', additions: 120, deletions: 0, changes: 120, status: 'added' },
        { filename: 'package.json', additions: 0, deletions: 1, changes: 1, status: 'modified' },
      ],
      additions: 430, deletions: 1, changed_files: 3,
      complexity: 38, effort: 16,
      complexityBreakdown: { score: 38, label: 'moderate', totalFiles: 3, relevantFiles: 3, ignoredFiles: 0, totalAdditions: 430, totalDeletions: 1, weightedChurn: 310, fileSpread: 3, intensity: 0.5, topFiles: [{ filename: 'src/components/VirtualList.tsx', weight: 1.0, churn: 310, contribution: 80 }] },
      created_at: new Date(now - day * 4).toISOString(),
      updated_at: new Date(now - day * 0.2).toISOString(),
    },
    {
      id: 7, number: 9198, draft: false,
      title: 'Add middleware support for internationalized routing',
      html_url: 'https://github.com/vercel/next.js/pull/9198',
      repository_url: 'https://github.com/vercel/next.js',
      url: 'https://github.com/vercel/next.js',
      user: { login: 'sarah-chen' },
      labels: [{ name: 'feature', color: '0e8a16' }, { name: 'needs-design-review', color: 'c5def5' }],
      body: 'Adds `createIntlMiddleware` helper for automatic locale detection and redirect.\n\n- Detects user locale from cookie, header, or URL\n- Redirects to correct locale prefix\n- Supports path-prefixed and domain-based routing',
      mergeable_state: 'clean',
      buildStatus: { state: 'completed', conclusion: 'success' },
      reviews: [
        { state: 'COMMENTED', user: { login: 'marcus-johnson' }, submitted_at: new Date(now - day * 2).toISOString(), body: 'Could we support custom locale detection logic via options?' },
      ],
      comments: [{ user: { login: 'marcus-johnson' }, created_at: new Date(now - day * 2).toISOString(), body: 'This looks solid. One concern: performance impact on every request? We should benchmark.' }],
      files: [
        { filename: 'packages/next-intl/src/middleware.ts', additions: 180, deletions: 0, changes: 180, status: 'added' },
        { filename: 'packages/next-intl/src/__tests__/middleware.test.ts', additions: 90, deletions: 0, changes: 90, status: 'added' },
        { filename: 'docs/internationalization.md', additions: 55, deletions: 0, changes: 55, status: 'added' },
      ],
      additions: 325, deletions: 0, changed_files: 3,
      complexity: 32, effort: 14,
      complexityBreakdown: { score: 32, label: 'moderate', totalFiles: 3, relevantFiles: 2, ignoredFiles: 1, totalAdditions: 325, totalDeletions: 0, weightedChurn: 180, fileSpread: 3, intensity: 0.3, topFiles: [{ filename: 'packages/next-intl/src/middleware.ts', weight: 1.0, churn: 180, contribution: 66 }] },
      created_at: new Date(now - day * 8).toISOString(),
      updated_at: new Date(now - day * 0.1).toISOString(),
    },
    {
      id: 8, number: 9175, draft: false,
      title: 'fix: Image optimization buffer overflow on malformed SVGs',
      html_url: 'https://github.com/vercel/next.js/pull/9175',
      repository_url: 'https://github.com/vercel/next.js',
      url: 'https://github.com/vercel/next.js',
      user: { login: 'james-mitchell' },
      labels: [{ name: 'bug', color: 'd73a4a' }, { name: 'security', color: 'd93f0b' }],
      body: 'Critical security fix. Malformed SVGs could cause a buffer overflow in the image optimization pipeline.\n\nAdds input validation and size limits.',
      mergeable_state: 'clean',
      buildStatus: { state: 'completed', conclusion: 'success' },
      reviews: [
        { state: 'APPROVED', user: { login: 'elena-rodriguez' }, submitted_at: new Date(now - day * 0.8).toISOString() },
        { state: 'APPROVED', user: { login: 'andrew-burton' }, submitted_at: new Date(now - day * 0.7).toISOString() },
        { state: 'APPROVED', user: { login: 'priya-patel' }, submitted_at: new Date(now - day * 0.6).toISOString() },
      ],
      comments: [{ user: { login: 'elena-rodriguez' }, created_at: new Date(now - day * 0.8).toISOString(), body: 'Good catch. We should also add fuzz testing for the image pipeline.' }],
      files: [
        { filename: 'packages/next/src/image-optimizer.ts', additions: 30, deletions: 8, changes: 38, status: 'modified' },
        { filename: 'packages/next/src/__tests__/image-optimizer-security.test.ts', additions: 95, deletions: 0, changes: 95, status: 'added' },
      ],
      additions: 125, deletions: 8, changed_files: 2,
      complexity: 18, effort: 8,
      complexityBreakdown: { score: 18, label: 'low', totalFiles: 2, relevantFiles: 2, ignoredFiles: 0, totalAdditions: 125, totalDeletions: 8, weightedChurn: 30, fileSpread: 2, intensity: 0.2, topFiles: [{ filename: 'packages/next/src/__tests__/image-optimizer-security.test.ts', weight: 0.2, churn: 0, contribution: 0 }] },
      created_at: new Date(now - day * 2).toISOString(),
      updated_at: new Date(now - day * 0.6).toISOString(),
    },
    {
      id: 9, number: 9150, draft: false,
      title: 'feat: App Router incremental adoption guide',
      html_url: 'https://github.com/vercel/next.js/pull/9150',
      repository_url: 'https://github.com/vercel/next.js',
      url: 'https://github.com/vercel/next.js',
      user: { login: 'elena-rodriguez' },
      labels: [{ name: 'documentation', color: '0075ca' }],
      body: 'Comprehensive guide for migrating Pages Router apps to App Router incrementally.\n\nIncludes: routing migration, data fetching patterns, layout nesting, and common pitfalls.',
      mergeable_state: 'clean',
      buildStatus: { state: 'completed', conclusion: 'success' },
      reviews: [
        { state: 'APPROVED', user: { login: 'sarah-chen' }, submitted_at: new Date(now - day * 0.3).toISOString() },
      ],
      comments: [],
      files: [
        { filename: 'docs/app-router-migration.md', additions: 450, deletions: 0, changes: 450, status: 'added' },
        { filename: 'examples/app-router-migration/example.tsx', additions: 85, deletions: 0, changes: 85, status: 'added' },
      ],
      additions: 535, deletions: 0, changed_files: 2,
      complexity: 8, effort: 4,
      complexityBreakdown: { score: 8, label: 'trivial', totalFiles: 2, relevantFiles: 0, ignoredFiles: 2, totalAdditions: 535, totalDeletions: 0, weightedChurn: 0, fileSpread: 2, intensity: 0, topFiles: [] },
      created_at: new Date(now - day * 3).toISOString(),
      updated_at: new Date(now - day * 0.3).toISOString(),
    },
    {
      id: 10, number: 387, draft: false,
      title: 'Add `backdrop-blur` and `backdrop-brightness` utilities',
      html_url: 'https://github.com/tailwindlabs/tailwindcss/pull/387',
      repository_url: 'https://github.com/tailwindlabs/tailwindcss',
      url: 'https://github.com/tailwindlabs/tailwindcss',
      user: { login: 'andrew-burton' },
      labels: [{ name: 'feature', color: '0e8a16' }],
      body: 'Implements backdrop-filter CSS utilities: `backdrop-blur-sm`, `backdrop-blur`, `backdrop-blur-md`, `backdrop-blur-lg`, `backdrop-blur-xl`, and `backdrop-brightness-*`.',
      mergeable_state: 'clean',
      buildStatus: { state: 'completed', conclusion: 'success' },
      reviews: [
        { state: 'APPROVED', user: { login: 'lisa-anderson' }, submitted_at: new Date(now - day * 1).toISOString() },
        { state: 'COMMENTED', user: { login: 'marcus-johnson' }, submitted_at: new Date(now - day * 1.5).toISOString() },
      ],
      comments: [{ user: { login: 'marcus-johnson' }, created_at: new Date(now - day * 1.5).toISOString(), body: 'Should we also add `backdrop-saturate` and `backdrop-grayscale`?' }],
      files: [
        { filename: 'src/plugins/backdropFilter.ts', additions: 150, deletions: 0, changes: 150, status: 'added' },
        { filename: 'src/config/backdrop.ts', additions: 64, deletions: 0, changes: 64, status: 'added' },
        { filename: 'tests/backdrop.test.ts', additions: 80, deletions: 0, changes: 80, status: 'added' },
      ],
      additions: 294, deletions: 0, changed_files: 3,
      complexity: 22, effort: 10,
      complexityBreakdown: { score: 22, label: 'low', totalFiles: 3, relevantFiles: 3, ignoredFiles: 0, totalAdditions: 294, totalDeletions: 0, weightedChurn: 150, fileSpread: 3, intensity: 0.2, topFiles: [{ filename: 'src/plugins/backdropFilter.ts', weight: 1.0, churn: 150, contribution: 60 }] },
      created_at: new Date(now - day * 6).toISOString(),
      updated_at: new Date(now - day * 1).toISOString(),
    },
    {
      id: 11, number: 372, draft: false,
      title: 'fix: Container queries not working with `@apply` in nested rules',
      html_url: 'https://github.com/tailwindlabs/tailwindcss/pull/372',
      repository_url: 'https://github.com/tailwindlabs/tailwindcss',
      url: 'https://github.com/tailwindlabs/tailwindcss',
      user: { login: 'lisa-anderson' },
      labels: [{ name: 'bug', color: 'd73a4a' }],
      body: 'Fixes a scoping issue where `@container` queries inside `@apply` directives were not being resolved correctly.',
      mergeable_state: 'clean',
      buildStatus: { state: 'completed', conclusion: 'success' },
      reviews: [
        { state: 'APPROVED', user: { login: 'andrew-burton' }, submitted_at: new Date(now - day * 0.5).toISOString() },
        { state: 'CHANGES_REQUESTED', user: { login: 'priya-patel' }, submitted_at: new Date(now - day * 1.2).toISOString(), body: 'The fix works but we need a test for the nested @apply case.' },
      ],
      comments: [{ user: { login: 'priya-patel' }, created_at: new Date(now - day * 1.2).toISOString(), body: 'Please add a test case for `@apply` with multiple nested `@container` queries.' }],
      files: [
        { filename: 'src/lib/resolveContainerQueries.ts', additions: 35, deletions: 20, changes: 55, status: 'modified' },
        { filename: 'tests/container-query.test.ts', additions: 45, deletions: 0, changes: 45, status: 'added' },
      ],
      additions: 80, deletions: 20, changed_files: 2,
      complexity: 14, effort: 6,
      complexityBreakdown: { score: 14, label: 'low', totalFiles: 2, relevantFiles: 2, ignoredFiles: 0, totalAdditions: 80, totalDeletions: 20, weightedChurn: 35, fileSpread: 2, intensity: 0.15, topFiles: [{ filename: 'src/lib/resolveContainerQueries.ts', weight: 1.0, churn: 35, contribution: 64 }] },
      created_at: new Date(now - day * 4).toISOString(),
      updated_at: new Date(now - day * 0.8).toISOString(),
    },
    {
      id: 12, number: 365, draft: false,
      title: 'v4: JIT engine rewrite with incremental compilation',
      html_url: 'https://github.com/tailwindlabs/tailwindcss/pull/365',
      repository_url: 'https://github.com/tailwindlabs/tailwindcss',
      url: 'https://github.com/tailwindlabs/tailwindcss',
      user: { login: 'marcus-johnson' },
      labels: [{ name: 'major', color: 'b60205' }, { name: 'performance', color: '008672' }],
      body: 'Complete rewrite of the JIT engine for v4. Incremental compilation reduces rebuilds from ~800ms to ~50ms on large projects.\n\n- File-system based caching\n- Dependency graph tracking\n- Selective recompilation',
      mergeable_state: 'dirty',
      buildStatus: { state: 'completed', conclusion: 'failure' },
      reviews: [
        { state: 'CHANGES_REQUESTED', user: { login: 'lisa-anderson' }, submitted_at: new Date(now - day * 2).toISOString(), body: 'The cache invalidation strategy needs work. See inline comments.' },
        { state: 'COMMENTED', user: { login: 'andrew-burton' }, submitted_at: new Date(now - day * 2.5).toISOString() },
      ],
      comments: [
        { user: { login: 'lisa-anderson' }, created_at: new Date(now - day * 2).toISOString(), body: 'Great performance wins but the cache layer introduces complexity. Let me know if you want to pair on the invalidation logic.' },
        { user: { login: 'andrew-burton' }, created_at: new Date(now - day * 2.5).toISOString(), body: 'The dependency graph looks solid. One question: how do we handle glob imports?' },
      ],
      files: [
        { filename: 'src/jit/compiler.ts', additions: 520, deletions: 0, changes: 520, status: 'added' },
        { filename: 'src/jit/cache.ts', additions: 180, deletions: 0, changes: 180, status: 'added' },
        { filename: 'src/jit/graph.ts', additions: 260, deletions: 0, changes: 260, status: 'added' },
        { filename: 'src/jit/__tests__/compiler.test.ts', additions: 200, deletions: 0, changes: 200, status: 'added' },
      ],
      additions: 1160, deletions: 0, changed_files: 4,
      complexity: 72, effort: 35,
      complexityBreakdown: { score: 72, label: 'high', totalFiles: 4, relevantFiles: 4, ignoredFiles: 0, totalAdditions: 1160, totalDeletions: 0, weightedChurn: 520, fileSpread: 4, intensity: 0.8, topFiles: [{ filename: 'src/jit/compiler.ts', weight: 1.0, churn: 520, contribution: 50 }, { filename: 'src/jit/graph.ts', weight: 1.0, churn: 260, contribution: 25 }] },
      created_at: new Date(now - day * 14).toISOString(),
      updated_at: new Date(now - day * 2).toISOString(),
    },
    {
      id: 13, number: 358, draft: true,
      title: 'Arbitrary value support for `inset-*` utilities',
      html_url: 'https://github.com/tailwindlabs/tailwindcss/pull/358',
      repository_url: 'https://github.com/tailwindlabs/tailwindcss',
      url: 'https://github.com/tailwindlabs/tailwindcss',
      user: { login: 'priya-patel' },
      labels: [{ name: 'enhancement', color: 'a2eeef' }],
      body: 'Allows arbitrary CSS values for inset utilities: `inset-[5px]`, `inset-x-[calc(50%-10px)]`, etc.',
      mergeable_state: 'clean',
      buildStatus: { state: 'pending', conclusion: undefined },
      reviews: [
        { state: 'COMMENTED', user: { login: 'lisa-anderson' }, submitted_at: new Date(now - day * 3).toISOString(), body: 'The parsing logic looks correct. Make sure to handle negative values.' },
      ],
      comments: [],
      files: [
        { filename: 'src/plugins/inset.ts', additions: 60, deletions: 15, changes: 75, status: 'modified' },
        { filename: 'tests/inset-arbitrary.test.ts', additions: 90, deletions: 0, changes: 90, status: 'added' },
      ],
      additions: 150, deletions: 15, changed_files: 2,
      complexity: 12, effort: 5,
      complexityBreakdown: { score: 12, label: 'low', totalFiles: 2, relevantFiles: 2, ignoredFiles: 0, totalAdditions: 150, totalDeletions: 15, weightedChurn: 60, fileSpread: 2, intensity: 0.1, topFiles: [{ filename: 'src/plugins/inset.ts', weight: 1.0, churn: 60, contribution: 100 }] },
      created_at: new Date(now - day * 5).toISOString(),
      updated_at: new Date(now - day * 3).toISOString(),
    },
    {
      id: 14, number: 9205, draft: false,
      title: 'feat: Static export with dynamic route fallback',
      html_url: 'https://github.com/vercel/next.js/pull/9205',
      repository_url: 'https://github.com/vercel/next.js',
      url: 'https://github.com/vercel/next.js',
      user: { login: 'david-kim' },
      labels: [{ name: 'feature', color: '0e8a16' }],
      body: 'Adds `fallback: "blocking"` support for static exports, so ungenerated paths get server-rendered on first request and cached thereafter.',
      mergeable_state: 'clean',
      buildStatus: { state: 'completed', conclusion: 'success' },
      reviews: [
        { state: 'COMMENTED', user: { login: 'priya-patel' }, submitted_at: new Date(now - day * 1.5).toISOString() },
      ],
      comments: [],
      files: [
        { filename: 'packages/next/src/export/worker.ts', additions: 95, deletions: 30, changes: 125, status: 'modified' },
        { filename: 'packages/next/src/export/__tests__/fallback.test.ts', additions: 70, deletions: 0, changes: 70, status: 'added' },
        { filename: 'docs/static-exports.md', additions: 40, deletions: 0, changes: 40, status: 'modified' },
      ],
      additions: 205, deletions: 30, changed_files: 3,
      complexity: 26, effort: 12,
      complexityBreakdown: { score: 26, label: 'low', totalFiles: 3, relevantFiles: 3, ignoredFiles: 0, totalAdditions: 205, totalDeletions: 30, weightedChurn: 95, fileSpread: 3, intensity: 0.3, topFiles: [{ filename: 'packages/next/src/export/worker.ts', weight: 1.0, churn: 95, contribution: 58 }] },
      created_at: new Date(now - day * 4).toISOString(),
      updated_at: new Date(now - day * 1.2).toISOString(),
    },
    {
      id: 15, number: 4275, draft: false,
      title: 'Update contributing guidelines and PR template',
      html_url: 'https://github.com/facebook/react/pull/4275',
      repository_url: 'https://github.com/facebook/react',
      url: 'https://github.com/facebook/react',
      user: { login: 'james-mitchell' },
      labels: [{ name: 'documentation', color: '0075ca' }],
      body: 'Refreshes the CONTRIBUTING.md and adds a PR template with checklist.\n\nIncludes: testing requirements, sign-off process, and breaking change policy.',
      mergeable_state: 'clean',
      buildStatus: { state: 'completed', conclusion: 'success' },
      reviews: [
        { state: 'APPROVED', user: { login: 'sarah-chen' }, submitted_at: new Date(now - day * 0.1).toISOString() },
        { state: 'APPROVED', user: { login: 'marcus-johnson' }, submitted_at: new Date(now - day * 0.05).toISOString() },
      ],
      comments: [],
      files: [
        { filename: 'CONTRIBUTING.md', additions: 80, deletions: 60, changes: 140, status: 'modified' },
        { filename: '.github/PULL_REQUEST_TEMPLATE.md', additions: 45, deletions: 0, changes: 45, status: 'added' },
      ],
      additions: 125, deletions: 60, changed_files: 2,
      complexity: 5, effort: 3,
      complexityBreakdown: { score: 5, label: 'trivial', totalFiles: 2, relevantFiles: 0, ignoredFiles: 2, totalAdditions: 125, totalDeletions: 60, weightedChurn: 0, fileSpread: 2, intensity: 0, topFiles: [] },
      created_at: new Date(now - day * 2).toISOString(),
      updated_at: new Date(now - day * 0.05).toISOString(),
    },
  ];
}
